const PlayerData = {
    'sachin': 'Sachin Ramesh Tendulkar is a former international cricketer from India and a former captain of the Indian national team. He is widely regarded as one of the greatest batsmen in the history of cricket. He is the highest run scorer of all time in International cricket.',
    'dhoni': 'Mahendra Singh Dhoni, is a former Indian international cricketer who captained the Indian national team in limited-overs formats from 2007 to 2016 and in Test cricket from 2008 to 2014.',
    'yuvaraj': 'Yuvraj Singh is a former Indian cricketer who played internationally in all formats of the game. An all-rounder who bats left-handed in the middle order and bowls slow left-arm orthodox, Yuvraj is the son of former Indian fast bowler and Punjabi actor Yograj Singh.',
    'shewag': 'Virender Sehwag is a former Indian cricketer. Widely regarded as one of the most destructive batsmen of all time, Sehwag played as an aggressive right-handed opening batsman and also bowled part-time right-arm off-spin. He played his first One Day International in 1999 and joined the Indian test side in 2001.',
    'rickyPonting': 'Ricky Thomas Ponting AO is an Australian cricket coach, commentator, and former cricketer. He is considered the most successful captain in international cricket history, with 220 victories in 324 matches with a winning ratio of 67.91%.',
    'davidWarner': 'David Andrew Warner is an Australian international cricketer and a former captain of the Australian national team. A left-handed opening batsman, Warner is the first Australian cricketer in 132 years to be selected for a national team in any format without experience in first-class cricket.',
    'steveSmith': 'Steven Peter Devereux Smith is an Australian international cricketer and former captain of the Australian national team. Smith is consistently rated as one of the top-ranked Test batsmen in the world, according to the ICC Player Rankings. ',
    'brettLee': 'Brett Lee is an Australian former international cricketer, who played all three formats of the game. During his international career, Lee was recognised as one of the fastest bowlers in the world. His fastest delivery was measured at 161.1 km/h. ',
    'stuartBroad': 'Stuart Christopher John Broad, MBE is an English cricketer who plays Test cricket for the England cricket team and a former ODI and T20 captain.',
    'jamesAnderson': 'James Michael Anderson, OBE, is an English international cricketer who plays for Lancashire County Cricket Club and the England cricket team. Anderson is the all-time leading wicket-taker among fast bowlers and holds the record of most wickets for England in both Test and One-Day International cricket.',
    'benStokes': 'Benjamin Andrew Stokes OBE is an English international cricketer and current vice-captain of the England cricket team in Test cricket. Stokes was part of the England squad that won the 2019 Cricket World Cup.',
    'joeRoot': 'Joseph Edward Root MBE is an English international cricketer who is the current captain of England in Test cricket. He also represents Yorkshire domestically. As of August 2020 he is ranked in the top-ten in both Test and ODI batting in the ICC Player Rankings.',
};
export default PlayerData;